### ISSUE TITLE
Unhandled exception: ejecting and inserting new disc before Done ripping dialog box is closed

### ISSUE THREAD

**Issue by tjanas** [gchudov/cuetools.net#120] opened 2021-09-02 17:34 UTC
After ripping a disc and prompted with the following dialog box:
![image](https://user-images.githubusercontent.com/20304619/131889979-0cb8e93e-12a5-42df-866f-0e36d180546e.png)
if I eject the disc and place a new disc in that drive before pressing "OK" on that dialog box, CUERipper throws an Unhandled exception:
![image](https://user-images.githubusercontent.com/20304619/131890375-326eef8d-3258-4c41-b5a2-d755dd084c43.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at CUETools.Processor.CUEMetadata.CopyMetadata(CUEMetadata metadata)
   at CUERipper.frmCUERipper.UpdateOutputPath()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4069.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
CUERipper
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/CUERipper.exe
----------------------------------------
CUETools.Processor
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/CUETools.Processor.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
CUETools.Codecs
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/CUETools.Codecs.DLL
----------------------------------------
CUETools.CTDB
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/CUETools.CTDB.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.1.21818
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/Newtonsoft.Json.DLL
----------------------------------------
CUETools.Compression
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/CUETools.Compression.DLL
----------------------------------------
CUETools.Ripper
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/CUETools.Ripper.DLL
----------------------------------------
CUETools.Codecs.ALAC
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Codecs.ALAC.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
CUETools.Codecs.ffmpegdll
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Codecs.ffmpegdll.DLL
----------------------------------------
CUETools.Codecs.FLACCL
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Codecs.FLACCL.DLL
----------------------------------------
CUETools.Codecs.Flake
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Codecs.Flake.DLL
----------------------------------------
CUETools.Codecs.HDCD
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Codecs.HDCD.DLL
----------------------------------------
CUETools.Codecs.libFLAC
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Codecs.libFLAC.DLL
----------------------------------------
CUETools.Codecs.libmp3lame
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Codecs.libmp3lame.DLL
----------------------------------------
CUETools.Codecs.libwavpack
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Codecs.libwavpack.DLL
----------------------------------------
CUETools.Codecs.MACLib
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Codecs.MACLib.DLL
----------------------------------------
CUETools.Codecs.MPEG
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Codecs.MPEG.DLL
----------------------------------------
CUETools.Codecs.WMA
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Codecs.WMA.DLL
----------------------------------------
WindowsMediaLib
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/WindowsMediaLib.DLL
----------------------------------------
CUETools.Compression.Zip
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Compression.Zip.DLL
----------------------------------------
CUETools.Ripper.SCSI
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/CUETools.Ripper.SCSI.DLL
----------------------------------------
CUETools.CDImage
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/CUETools.CDImage.DLL
----------------------------------------
Bwg.Scsi
    Assembly Version: 0.0.7.1
    Win32 Version: 0.0.7.1
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/Bwg.Scsi.DLL
----------------------------------------
CUETools.Codecs.TTA
    Assembly Version: 2.1.9.0
    Win32 Version: 
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/x64/CUETools.Codecs.TTA.dll
----------------------------------------
CUETools.Compression.Rar
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/x64/CUETools.Compression.Rar.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
CUEControls
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/CUEControls.DLL
----------------------------------------
ProgressODoom
    Assembly Version: 1.0.7791.14056
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/ProgressODoom.DLL
----------------------------------------
CUETools.CTDB.Types
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/CUETools.CTDB.Types.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
CUETools.AccurateRip
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/CUETools.AccurateRip.DLL
----------------------------------------
Bwg.Logging
    Assembly Version: 0.0.7.1
    Win32 Version: 0.0.7.1
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/plugins/Bwg.Logging.DLL
----------------------------------------
Freedb
    Assembly Version: 1.0.0.1
    Win32 Version: 1.0.0.1
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/Freedb.DLL
----------------------------------------
taglib-sharp
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/taglib-sharp.DLL
----------------------------------------
CUETools.Parity
    Assembly Version: 2.1.9.0
    Win32 Version: 2.1.9.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/CUETools.Parity.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DeviceId
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/ROMS/RIPPING%20TOOLS/CUETools_2.1.9/DeviceId.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by RDamman** [comment] 2021-09-11 06:46
I cannot reproduce your problem. Can you tell which CD you have ripped first and which CD metadata you had selected? And what was the following CD?

**Comment by c72578** [comment] 2021-09-24 17:09
@tjanas A PR with a fix has been created by @RDamman.
You can find a build of CUETools there for testing: https://github.com/gchudov/cuetools.net/pull/124#issuecomment-926786310

**Comment by tjanas** [comment] 2021-09-24 18:35
> @tjanas A PR with a fix has been created by @RDamman.
> You can find a build of CUETools there for testing

Thanks! I tested this build, and it seems to resolve this issue.

**Closed** 2021-12-30 19:53 UTC
